name: production-deploy
on:
  push:
    branches: [main]

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'

      - name: Install packages
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Export static files
        run: yarn export

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: production
          folder: out
